# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Parser-LocalizeNewlines
version:      0.01
version_from: lib/Template/Parser/LocalizeNewlines.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Template:                      2.00
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
